# Generated by Django 2.2.6 on 2020-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='结束时间')),
                ('biz', models.CharField(max_length=32, verbose_name='业务')),
                ('machine_numbers', models.IntegerField(verbose_name='机器数')),
                ('result', models.BooleanField(verbose_name='状态')),
                ('script_id', models.IntegerField(verbose_name='脚本id')),
                ('log', models.TextField(verbose_name='日志详情')),
                ('status', models.TextField(default=-1, verbose_name='状态')),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=32, verbose_name='脚本名称')),
                ('script_content', models.TextField(verbose_name='脚本内容')),
                ('default_params', models.CharField(default='', max_length=64, verbose_name='默认参数')),
                ('script_desc', models.CharField(max_length=32, verbose_name='脚本描述')),
            ],
            options={
                'db_table': 'script',
            },
        ),
    ]
