# Generated by Django 2.2.6 on 2020-05-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': '执行记录', 'verbose_name_plural': '执行记录'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelTable(
            name='operation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='script',
            table=None,
        ),
    ]
